name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 pylint

      - name: Run flake8
        run: flake8 . --max-line-length=79

      - name: Run black
        run: black --check --diff .  # Remove || true to enforce formatting

      - name: Run pylint
        run: pylint **/*.py

  code-quality:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint mypy

      - name: Run pylint
        run: pylint **/*.py

      - name: Run mypy
        run: mypy . || true  # Remove || true if you want to enforce type checking

      - name: Run additional quality checks
        run: |
          echo "Additional code quality checks can be added here."

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: pytest

  merge:
    runs-on: ubuntu-latest
    needs: [lint, code-quality, test]  # Ensure all checks are successful before merging
    if: github.event_name == 'push' && github.ref == 'refs/heads/feature/*'  # Only run on push to feature branches
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Merge feature branch to dev
        run: |
          git checkout dev
          git merge --no-ff ${{ github.head_ref }}
          git push origin dev

