name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black pylint

      - name: Run flake8
        run: flake8 . --max-line-length=79

      - name: Run black
        run: black --check .

      - name: Run pylint
        run: pylint **/*.py

  format:
    runs-on: ubuntu-latest
    needs: lint
    if: failure()  # This job runs only if the lint job fails

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Reformat code with black
        run: black .

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Apply black formatting"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code-quality:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint mypy

      - name: Run pylint
        run: pylint **/*.py

      - name: Run mypy
        run: mypy . || true

      - name: Run additional quality checks
        run: |
          # Add any additional quality checks here, if needed
          echo "Additional code quality checks can be added here."

  test:
    runs-on: ubuntu-latest
    needs: lint
    if: success()  # This job runs only if the lint job succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run unit tests
        run: pytest

